spring.application.name=backend_springboot

spring.datasource.url=jdbc:mysql://localhost:3306/apartment_booking
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


rpcUrl=http://127.0.0.1:8545
privateKey=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

kycNftAddress=0x5FbDB2315678afecb367f032d93F642f64180aa3
propertyNftAddress=0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
marketplaceAddress=0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0

api_key_pinata=5c32687cc527429bba1d
api_secret_pinata=81606d877288320c8242e7f5c1d069921c365472fc59d6a9b7c43ad349b490bf

gemini.model=gemini-2.5-flash
gemini.api.key=AIzaSyDu-RDIP-tDYUq4D3tSMA00OcTKwv_xdrA