spring.application.name=backend_springboot

spring.datasource.url=jdbc:mysql://localhost:3306/apartment_booking
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


rpcUrl=http://127.0.0.1:8545

kycNftAddress=0x5b73C5498c1E3b4dbA84de0F1833c4a029d90519
propertyNftAddress=0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496
marketplaceAddress=0x34A1D3fff3958843C43aD80F30b94c510645C316
privateKey=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80